---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyubao.
--- DateTime: 2022/2/11 14:18
--- 判断周围没有敌人
---@class bt_con_aroundNoEnemy
local bt_con_aroundNoEnemy = SimpleClassUtil:class(ICondition)
---@param skillData SkillData
function bt_con_aroundNoEnemy:initData(skillData)
    self._condition = skillData._condition or {}
    self._r = self._condition[2] or 0
end
---@param blackBoard BlackBoard_BattleBase
function bt_con_aroundNoEnemy:doCondition(blackBoard,agent,dt)
    local result = Enum_BT.Node_ResultType.Success
    --- @type BattleEntityContext
    local _entityContext = agent._entityContext
    local enemy_list = _entityContext:getEnemyEntityList(blackBoard._campType)
    for _, character in pairs(enemy_list) do
        if  character and character:getData()._alive  then
           local pos =  character:getData()._position
            if Vector3.Distance(pos,blackBoard._position) < self._r then
                result = Enum_BT.Node_ResultType.Fail
                break
            end
        end
    end
    return result
end


return bt_con_aroundNoEnemy
