---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyubao.
--- DateTime: 2021/12/15 16:08
---

Mathf = require_path("Mathf", "battle/base/math3D/Mathf")
Vector3 = require_path("Mathf", "battle/base/math3D/Vector3")