---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyubao.
--- DateTime: 2021/12/17 17:40
---@class BattleProxy
local BattleProxy = {}

function BattleProxy:Init()

end
---进入布阵
function BattleProxy:EnterTeamSetUp(type)
    -- 打开布阵UI
    SetUpTeamProxy:OpenSetUpTeam(type)
    -- 加载场景

    -- 加载敌我 模型
end
---退出布阵
function BattleProxy:ExitTeamSetUp(type)

end
---进入战斗
function BattleProxy:EnterBattle()

end
---退出战斗
function BattleProxy:ExitBattle()

end
---结束战斗
function BattleProxy:EndBattle()

end
return BattleProxy

