// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: rpc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SLG {

  /// <summary>Holder for reflection information generated from rpc.proto</summary>
  public static partial class RpcReflection {

    #region Descriptor
    /// <summary>File descriptor for rpc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RpcReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CglycGMucHJvdG8SA1NMRxoJbXNnLnByb3RvGgxtc2dfd2YucHJvdG8aDm1z",
            "Z19jaGF0LnByb3RvGhJtc2dfYnVpbGRpbmcucHJvdG8yPwoPZ2JDZW50ZXJf",
            "UmVtb3RlEiwKB09uTG9naW4SEi5TTEcuVXNlckVudGVySW5mbxoNLlNMRy5M",
            "b2dpblJldDKtAgoPd2JTY2VuZV9IYW5kbGVyEi4KC1N0YXJ0QmF0dGxlEg8u",
            "U0xHLkF0dGFja0RhdGEaDi5TTEcuUmV0dXJuTXNnEikKClZpZXdOZXdQb3MS",
            "Cy5TTEcuQ3VyUG9zGg4uU0xHLlJldHVybk1zZxIvCgpTdGFydE1hcmNoEhEu",
            "U0xHLldzTWFyY2hFdmVudBoOLlNMRy5SZXR1cm5Nc2cSKQoLQ3JlYXRlVHJv",
            "b3ASCi5TTEcuVHJvb3AaDi5TTEcuUmV0dXJuTXNnEi8KD1N0YXJ0VHJvb3BN",
            "YXJjaBIMLlNMRy5Xc01hcmNoGg4uU0xHLlJldHVybk1zZxIyCg9Ucm9vcFJl",
            "dHVybkhvbWUSDy5TTEcuT3BlcmF0ZU1zZxoOLlNMRy5SZXR1cm5Nc2cyrAEK",
            "DndiU2NlbmVfUmVtb3RlEjQKCkVudGVyU2NlbmUSEi5TTEcuRW50ZXJTY2Vu",
            "ZVJlcRoSLlNMRy5FbnRlclNjZW5lUnNwEjMKDk9uQmF0dGxlRmluaXNoEhEu",
            "U0xHLkJhdHRsZVJlc3VsdBoOLlNMRy5SZXR1cm5Nc2cSLwoKU3RhcnRNYXJj",
            "aBIRLlNMRy5Xc01hcmNoRXZlbnQaDi5TTEcuUmV0dXJuTXNnMn8KDndmR2F0",
            "ZV9IYW5kbGVyEjcKC0VudGVyU2VydmVyEhMuU0xHLkVudGVyU2VydmVyUmVx",
            "GhMuU0xHLkVudGVyU2VydmVyUnNwEjQKCkNyZWF0ZVJvbGUSEi5TTEcuQ3Jl",
            "YXRlUm9sZVJlcRoSLlNMRy5DcmVhdGVSb2xlUnNwMkMKD3diQmF0dGxlX1Jl",
            "bW90ZRIwCg1PblN0YXJ0QmF0dGxlEg8uU0xHLkJhdHRsZURhdGEaDi5TTEcu",
            "UmV0dXJuTXNnMkgKFXdiU2NlbmVfVW5pb25fSGFuZGxlchIvCg5HZXRXc1Vu",
            "aW9uTGlzdBILLlNMRy5DdXJQb3MaEC5TTEcuV3NVbmlvbkxpc3QysQEKBkNs",
            "aWVudBIdCgZPbkNoYXQSEy5TTEcuU2luZ2xlQ2hhdEluZm8SHwoNT25Xc09i",
            "akNyZWF0ZRIOLlNMRy5Xc09iakluZm8SHwoNT25Xc09iakRlbGV0ZRIOLlNM",
            "Ry5Xc09iakluZm8SIQoPT25QbGF5ZXJWaWV3Q2hnEg4uU0xHLldzT2JqTGlz",
            "dBIjCg5PbldzTWFyY2hFdmVudBIRLlNMRy5Xc01hcmNoRXZlbnQyvgIKDXdD",
            "aGF0X0hhbmRsZXISMQoJQ2hhdEVudHJ5EhMuU0xHLlNpbmdsZUNoYXRJbmZv",
            "Gg8uU0xHLkNoYXRSZXR1cm4SOAoUR2V0Q2hhdERhdGFCeVJlcXVlc3QSEC5T",
            "TEcuQ2hhdFJlcXVlc3QaDi5TTEcuQ2hhdERhdGFzEjwKDk9wZXJhdGVDaGFu",
            "bmVsEhkuU0xHLkNoYW5uZWxPcGVyYXRpb25JbmZvGg8uU0xHLkNoYXRSZXR1",
            "cm4SPwoTT3BlcmF0ZUNoYW5uZWxHcm91cBIXLlNMRy5Hcm91cE9wZXJhdGlv",
            "bkluZm8aDy5TTEcuQ2hhdFJldHVybhJBChdHZXRQbGF5ZXJBbGxDaGFubmVs",
            "RGF0YRIOLlNMRy5TaW1wbGVNc2caFi5TTEcuUGxheWVyQ2hhbm5lbERhdGEy",
            "gQEKDHdDaGF0X1JlbW90ZRI3CgxQbGF5ZXJPbmxpbmUSFi5TTEcuUGxheWVy",
            "SW5mb0ZvckNoYXQaDy5TTEcuQ2hhdFJldHVybhI4Cg1QbGF5ZXJPZmZsaW5l",
            "EhYuU0xHLlBsYXllckluZm9Gb3JDaGF0Gg8uU0xHLkNoYXRSZXR1cm4yngIK",
            "EndiQnVpbGRpbmdfSGFuZGxlchI3ChFVcGRhdGVBbGxMb2NhdGlvbhISLlNM",
            "Ry5CdWlsZGluZ3NJbmZvGg4uU0xHLlJldHVybk1zZxIwCg5VcGRhdGVMb2Nh",
            "dGlvbhIOLlNMRy5CbG9ja0luZm8aDi5TTEcuUmV0dXJuTXNnEjgKEkdldEJ1",
            "aWxkaW5nc0J5VHlwZRIOLlNMRy5TaW1wbGVNc2caEi5TTEcuQnVpbGRpbmdz",
            "SW5mbxI1Cg9HZXRBbGxCdWlsZGluZ3MSDi5TTEcuU2ltcGxlTXNnGhIuU0xH",
            "LkJ1aWxkaW5nc0luZm8SLAoKRG9SZXNlYXJjaBIOLlNMRy5TaW1wbGVNc2ca",
            "Di5TTEcuU2ltcGxlTXNnMk0KEXdiQnVpbGRpbmdfUmVtb3RlEjgKC1BsYXll",
            "ckxvZ2luEhUuU0xHLkxvZ2luQnVpbGRpbmdSZXEaEi5TTEcuQnVpbGRpbmdz",
            "SW5mb2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SLG.MsgReflection.Descriptor, global::SLG.MsgWfReflection.Descriptor, global::SLG.MsgChatReflection.Descriptor, global::SLG.MsgBuildingReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
