---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyubao.
--- DateTime: 2021/12/30 16:22
---@class MoveSystem:SimpleClassUtil
local MoveSystem = SimpleClassUtil:class()

local eventHandleMap = {
    [EventType.Event_Battle_Render_Move_Line] = "moveLineHandle",
}

function MoveSystem:initialize(go_model)
    ---@type BattleRenderCharacter []
    self._entityMap = {}

    self._eventListenerList = {}

    self:registerMsg()

end


function MoveSystem:moveLineHandle(data)

end




return MoveSystem